<a href="https://colab.research.google.com/github/salmanmkc/-mgt-Adding-Simple-Provider/blob/master/00_pytorch_fundamentals_exercises_my_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
random = torch.rand(7, 7)

random
random.size() # can also do random.shape

torch.Size([7, 7])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
random_2 = torch.rand(1, 7)


# Perform matrix multiplication ]

# THIS WORKS
# torch.mm(random, random_2.T)

# another way to do this
print(random_2)
print(random_2.T)
print(torch.transpose(random_2, 0, 1))
# the 2nd and third parameters are the dimensions to swap
print(random_2.T == torch.transpose(random_2, 0, 1))
# torch.mm(random, torch.transpose(random_2, 0, 1))

tensor([[0.5949, 0.7956, 0.7635, 0.2137, 0.3066, 0.0386, 0.5220]])
tensor([[0.5949],
        [0.7956],
        [0.7635],
        [0.2137],
        [0.3066],
        [0.0386],
        [0.5220]])
tensor([[0.5949],
        [0.7956],
        [0.7635],
        [0.2137],
        [0.3066],
        [0.0386],
        [0.5220]])
tensor([[True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(seed=RANDOM_SEED)

# Create two random tensors
random_tensor_3 = torch.rand(7, 7)
print(random_tensor_3)

torch.manual_seed(seed=RANDOM_SEED)
random_tensor_4 = torch.rand(1, 7)
print(random_tensor_4)
# Matrix multiply tensors
# tranpose the second tensor in this

#first easier way
first_mm = torch.mm(random_tensor_3, random_tensor_4.T)
second_mm = torch.mm(random_tensor_3, torch.transpose(random_tensor_4, 0, 1))

print(first_mm)
print(second_mm)
print(first_mm == second_mm)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])
tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])
tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])
tensor([[True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True]])


In [ ]:
random_tensor_4 = torch.rand(1, 7)
print(random_tensor_4)

tensor([[0.1100, 0.2121, 0.9704, 0.8369, 0.2820, 0.3742, 0.0237]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
MANUAL_SEED = 1234
torch.cuda.manual_seed(seed=MANUAL_SEED)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed


# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"



# Create two random tensors on GPU
torch.cuda.manual_seed(seed=MANUAL_SEED)
randomOnGpu = torch.rand(12, 12, device=device)
print(randomOnGpu)

torch.cuda.manual_seed(seed=MANUAL_SEED)
randomOnGpu2 = torch.rand(12, 6, device=device)



tensor([[0.1272, 0.8167, 0.5440, 0.6601, 0.2721, 0.9737, 0.3903, 0.3394, 0.5451,
         0.7312, 0.3864, 0.5959],
        [0.7578, 0.2126, 0.7198, 0.9845, 0.5518, 0.0981, 0.0582, 0.5839, 0.1083,
         0.9461, 0.3170, 0.8328],
        [0.6676, 0.2886, 0.9022, 0.8115, 0.1784, 0.9534, 0.1486, 0.3882, 0.7977,
         0.1752, 0.5777, 0.1949],
        [0.8499, 0.3125, 0.2156, 0.0383, 0.4934, 0.3138, 0.3121, 0.5664, 0.1266,
         0.7097, 0.0040, 0.5147],
        [0.2811, 0.4441, 0.0915, 0.3322, 0.3984, 0.9881, 0.0936, 0.3067, 0.0523,
         0.2162, 0.0307, 0.4602],
        [0.1048, 0.1429, 0.7458, 0.5464, 0.6944, 0.8088, 0.2945, 0.8648, 0.1688,
         0.3534, 0.3706, 0.5675],
        [0.9595, 0.6452, 0.7709, 0.2298, 0.1510, 0.2425, 0.8819, 0.5867, 0.1070,
         0.6552, 0.2062, 0.3814],
        [0.6594, 0.4250, 0.4623, 0.7210, 0.9497, 0.3176, 0.1693, 0.5473, 0.4224,
         0.8215, 0.6750, 0.6834],
        [0.0144, 0.0734, 0.5473, 0.5675, 0.3279, 0.3553, 0.0989, 0.7877, 0.1829,


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
multiplied = torch.mm(randomOnGpu, randomOnGpu2)

print('\nMultiplied')
print(multiplied)



Multiplied
tensor([[1.9874, 2.6898, 2.6037, 3.2494, 2.3935, 3.4859],
        [1.7943, 3.0690, 2.2518, 3.8855, 1.7848, 3.8905],
        [1.7954, 2.6560, 2.8064, 3.5882, 2.5025, 3.6355],
        [1.4679, 2.2706, 1.7651, 2.2869, 1.1745, 2.7349],
        [1.0596, 1.7872, 1.8202, 1.8759, 1.3127, 2.0208],
        [2.0567, 2.4350, 2.5817, 3.2907, 1.9542, 3.0238],
        [2.2663, 2.6541, 2.3098, 3.1213, 1.9605, 3.1461],
        [2.1057, 3.0894, 2.9175, 4.0328, 2.1815, 4.5724],
        [1.3961, 1.9592, 1.8143, 2.7222, 1.5641, 2.5982],
        [1.9136, 2.6241, 2.5480, 3.1874, 2.5220, 3.7092],
        [1.9471, 2.8929, 2.9068, 4.0200, 2.2879, 4.3008],
        [1.9062, 2.7801, 2.1721, 3.1302, 2.2555, 3.3350]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
print(torch.max(multiplied))
# Find min
print(torch.min(multiplied))


tensor(4.5724, device='cuda:0')
tensor(1.0596, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max - two ways
print(torch.argmax(multiplied))
print(multiplied.argmax())

# Find arg min - two ways
print(torch.argmin(multiplied))
print(multiplied.argmin())

tensor(47, device='cuda:0')
tensor(47, device='cuda:0')
tensor(24, device='cuda:0')
tensor(24, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
MANUAL_SEED = 7


# Create random tensor
random_tensor_5 = torch.rand(1, 1, 1, 10)
print(random_tensor_5)

# Remove single dimensions
removed_all_single_dimensions = random_tensor_5.squeeze()
print(removed_all_single_dimensions)

# Print out tensors and their shapes
print('\n\nBefore squeezing/removing all 1 dimensions')
print(random_tensor_5)
print(random_tensor_5.size())

print('\nAfter squeeinzg/removing all 1 dimensions')
print(removed_all_single_dimensions)
print(removed_all_single_dimensions.size())



tensor([[[[0.4012, 0.5627, 0.3858, 0.4965, 0.5638, 0.1089, 0.2379, 0.9037,
           0.0942, 0.4641]]]])
tensor([0.4012, 0.5627, 0.3858, 0.4965, 0.5638, 0.1089, 0.2379, 0.9037, 0.0942,
        0.4641])


Before squeezing/removing all 1 dimensions
tensor([[[[0.4012, 0.5627, 0.3858, 0.4965, 0.5638, 0.1089, 0.2379, 0.9037,
           0.0942, 0.4641]]]])
torch.Size([1, 1, 1, 10])

After squeeinzg/removing all 1 dimensions
tensor([0.4012, 0.5627, 0.3858, 0.4965, 0.5638, 0.1089, 0.2379, 0.9037, 0.0942,
        0.4641])
torch.Size([10])
